name: flutter_google_maps
version: 4.1.0
homepage: https://github.com/marchdev-tk/flutter_google_maps
description: A Flutter plugin for integrating Google Maps in iOS, Android and Web applications. It is a wrapper of google_maps_flutter for Mobile and google_maps for Web.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_polyline_algorithm: ^3.0.0
  google_maps_flutter: ^0.5.30
  google_directions_api: ^0.6.0
  google_maps: ^3.4.4
  http: ^0.13.3
  flinq: ^2.0.1
  uuid: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/marker_a.png
    - assets/images/marker_b.png